### ISSUE TITLE
SPM / TIM / IM1+IM2

### ISSUE THREAD

**Issue by lorincmeszaros** [openearth/hybrid-spm#7]
MWTL and satellite measures SPM. The model produces IM1, IM2, and TIM (Total Inorganic Matter).

 The D-Water_Quality_Processes_Technical_Reference_Manual.pdf describes the sediment related processes:

![image](https://user-images.githubusercontent.com/64486996/200687749-f25c90ef-9195-47ad-9b27-695b7900cadc.png)

![image](https://user-images.githubusercontent.com/64486996/200687965-20015799-fece-4d3d-88a5-f5b17d086cb6.png)

Meaning that IM1 and IM2 are the concentration of inorganic matter fractions in the flow element, and TIM is the concnetration of total inorganic matter in the flow element. The total suspended sediment (TPM or SS) includes the concentration of total part. matter without algae (TIM is part of this) plus organic dry mattter / total algae biomass conc. on a dry matter basis (AlgDM). Based on this, the closest approx. is still TIM.

**Comment by lorincmeszaros** [comment]
@luukvanderheijden can you maybe double check woth Julia? Last year I think I asked her if TIM is okay and as I remember she agreed..

**Comment by luukvanderheijden** [comment]
> @luukvanderheijden can you maybe double check woth Julia? Last year I think I asked her if TIM is okay and as I remember she agreed..

@lorincmeszaros, checked with Bob Smits. TIM = IM1 + IM2 (with a ratio behind it)
